import { useEffect, useMemo, useState } from "react";
import { api } from "../api/backend";
import { IrisMark } from "./IrisMark";
import { PlaidLinkButton } from "./PlaidLink";
import "./IrisApplication.css";

type Domain = "home" | "money" | "cashflow" | "spending" | "bills" | "income" | "debt" | "goals" | "roundups" | "networth" | "insights" | "iris" | "reports" | "data" | "settings";
type Page = { id: string; domain: Domain; label: string; description: string };
type Finding = { title: string; statement: string; evidence?: string; state?: string; date?: string; where?: string; why?: string };

const pages: Page[] = [
  { id: "home", domain: "home", label: "Home", description: "Your current financial state" },
  { id: "money", domain: "money", label: "Money", description: "Accounts, assets and liabilities" },
  { id: "money/accounts", domain: "money", label: "Accounts", description: "Every connected account" },
  { id: "money/timeline", domain: "money", label: "Money timeline", description: "How your financial state changes through time" },
  { id: "cashflow", domain: "cashflow", label: "Cash Flow", description: "Inflows, outflows and liquidity" },
  { id: "cashflow/forecast", domain: "cashflow", label: "Forecast", description: "Evidence-based forward model" },
  { id: "spending", domain: "spending", label: "Spending", description: "Behavior, categories and change" },
  { id: "spending/transactions", domain: "spending", label: "Transactions", description: "Observed transaction history" },
  { id: "spending/anomalies", domain: "spending", label: "Anomalies", description: "Unusual observed behavior" },
  { id: "bills", domain: "bills", label: "Bills & obligations", description: "Recurring and expected commitments" },
  { id: "bills/calendar", domain: "bills", label: "Obligation calendar", description: "Expected financial pressure by date" },
  { id: "income", domain: "income", label: "Income", description: "Observed inflows and income signals" },
  { id: "income/history", domain: "income", label: "Income history", description: "Income observations through time" },
  { id: "debt", domain: "debt", label: "Debt", description: "Credit, loans and repayment state" },
  { id: "debt/utilization", domain: "debt", label: "Utilization", description: "Observed and calculated credit pressure" },
  { id: "goals", domain: "goals", label: "Goals", description: "Financial objectives and evidence" },
  { id: "roundups", domain: "roundups", label: "Round-Ups", description: "Simulated savings opportunities" },
  { id: "networth", domain: "networth", label: "Net Worth", description: "Assets, liabilities and change" },
  { id: "networth/history", domain: "networth", label: "Net Worth history", description: "Observed state through time" },
  { id: "insights", domain: "insights", label: "Insights", description: "Evidence-backed findings" },
  { id: "iris", domain: "iris", label: "Iris", description: "Briefing, explanations and decisions" },
  { id: "iris/findings", domain: "iris", label: "Findings", description: "Risks, opportunities and changes" },
  { id: "iris/timeline", domain: "iris", label: "Financial timeline", description: "Relationships across time" },
  { id: "iris/education", domain: "iris", label: "Education", description: "Understand the financial concepts behind your state" },
  { id: "reports", domain: "reports", label: "Reports", description: "Saved analytical views" },
  { id: "data", domain: "data", label: "Data & Plaid", description: "Provider data, coverage and evidence" },
  { id: "data/evidence", domain: "data", label: "Evidence", description: "Source, freshness and lineage" },
  { id: "data/sync", domain: "data", label: "Sync history", description: "Observed provider synchronization" },
  { id: "settings", domain: "settings", label: "Settings", description: "Application and data controls" },
];
const primary: Domain[] = ["home", "money", "cashflow", "spending", "bills", "income", "debt", "goals", "roundups", "networth", "insights", "iris", "reports", "data"];
const money = (n: number | null | undefined) => n == null ? "—" : `${n < 0 ? "−" : ""}$${Math.abs(n).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const signed = (n: number | null | undefined) => n == null ? "—" : `${n >= 0 ? "+" : "−"}$${Math.abs(n).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const label = (s: string) => s.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
const evidenceLabel = (s?: string) => ({ observed: "Observed", calculated: "Calculated", inferred: "Iris inference", limited: "Limited evidence", insufficient_evidence: "Insufficient evidence" } as Record<string, string>)[s ?? "calculated"] ?? label(s ?? "calculated");
function Metric({ name, value, note }: { name: string; value: string; note?: string }) { return <div className="ia-metric"><span>{name}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>; }
function Evidence({ state }: { state?: string }) { return <span className={`ia-evidence ${state ?? "calculated"}`}>{evidenceLabel(state)}</span>; }
function Temporal({ date, role }: { date?: string; role: string }) { if (!date) return null; const d = new Date(date); return <span className="ia-temporal"><b>{role}</b><span>{Number.isNaN(d.getTime()) ? date : d.toLocaleString("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" })}</span></span>; }

export function IrisApplication() {
  const [page, setPage] = useState(() => window.location.hash.replace(/^#\/?/, "") || "home");
  const [overview, setOverview] = useState<any>(); const [intel, setIntel] = useState<any>(); const [products, setProducts] = useState<any>();
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string>(); const [drawer, setDrawer] = useState<Finding>();
  const [query, setQuery] = useState(""); const [navOpen, setNavOpen] = useState(false);
  const load = async () => { setLoading(true); setError(undefined); try { const o = await api.getOverview(); setOverview(o); const [i, p] = await Promise.all([o.accounts?.length ? api.getIntelligence() : Promise.resolve(null), api.getPlaidProducts()]); setIntel(i); setProducts(p); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load Iris"); } finally { setLoading(false); } };
  useEffect(() => { void load(); const onHash = () => setPage(window.location.hash.replace(/^#\/?/, "") || "home"); window.addEventListener("hashchange", onHash); return () => window.removeEventListener("hashchange", onHash); }, []);
  const go = (id: string) => { window.location.hash = id; setNavOpen(false); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const current = pages.find(p => p.id === page) ?? pages[0];
  const findings = useMemo<Finding[]>(() => [...(intel?.reasoning?.risks ?? []).map((x: any) => ({ title: "Risk", statement: x.statement, evidence: x.evidence, state: "calculated", why: "Iris elevated this finding from available evidence and its reasoning rules." })), ...(intel?.reasoning?.opportunities ?? []).map((x: any) => ({ title: "Opportunity", statement: x.statement, evidence: x.evidence, state: "calculated", why: "Iris identified this possibility from the evidence available to its reasoning layer." }))], [intel]);
  const filteredPages = query.trim() ? pages.filter(p => `${p.label} ${p.description}`.toLowerCase().includes(query.toLowerCase())) : [];
  if (loading) return <div className="ia-loading"><IrisMark size={58} color="#111"/><strong>Building Iris</strong><p>Assembling your financial life state from authorized evidence…</p></div>;
  if (!overview) return <div className="ia-loading"><strong>Iris could not load</strong><p>{error}</p><button onClick={() => void load()}>Try again</button></div>;
  return <div className="ia-app"><aside className={`ia-sidebar ${navOpen ? "open" : ""}`}><button className="ia-brand" onClick={() => go("home")}><IrisMark size={31} color="#111"/><span><b>iBag</b><small>Intelligence by Iris</small></span></button><div className="ia-nav-label">WORKSPACES</div><nav>{primary.map(id => { const p = pages.find(x => x.id === id)!; return <button key={id} className={current.domain === id ? "active" : ""} onClick={() => go(id)}><span>{p.label}</span>{id === "iris" && findings.length > 0 && <em>{findings.length}</em>}</button>; })}</nav><div className="ia-nav-label">SYSTEM</div><button className={current.domain === "settings" ? "ia-system active" : "ia-system"} onClick={() => go("settings")}>Settings</button><footer><span className="ia-live"/>Live intelligence<small>Real authorized data · read-only Phase 1</small></footer></aside><main className="ia-main"><header className="ia-header"><button className="ia-menu" onClick={() => setNavOpen(v => !v)}>☰</button><div className="ia-breadcrumb"><b>{current.label}</b><span>{current.description}</span></div><div className="ia-actions"><label className="ia-search"><span>⌕</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Find anything in iBag" />{query && <div className="ia-search-results">{filteredPages.slice(0, 8).map(p => <button key={p.id} onClick={() => { go(p.id); setQuery(""); }}>{p.label}<small>{p.description}</small></button>)}{!filteredPages.length && <p>No workspace matches that search.</p>}</div>}</label><PlaidLinkButton onSuccess={() => void load()}/><button className="ia-data" onClick={() => go("data")}>Data</button></div></header>{error && <div className="ia-alert"><b>Data refresh issue</b><span>{error}</span><button onClick={() => void load()}>Retry</button></div>}<div className="ia-content">{!overview.accounts?.length ? <Connect onConnect={() => void load()}/> : <PageView page={page} overview={overview} intel={intel} products={products} findings={findings} go={go} open={setDrawer}/>}</div><div className="ia-mobile-nav">{["home", "money", "spending", "bills", "iris"].map(id => <button key={id} className={current.domain === id ? "active" : ""} onClick={() => go(id)}>{pages.find(p => p.id === id)?.label}</button>)}</div></main>{drawer && <EvidenceDrawer finding={drawer} close={() => setDrawer(undefined)}/>}</div>;
}
function PageView({ page, overview: o, intel: i, products, findings, go, open }: { page: string; overview: any; intel: any; products: any; findings: Finding[]; go: (id: string) => void; open: (f: Finding) => void }) {
  if (page === "home") return <Home o={o} i={i} findings={findings} go={go} open={open}/>; if (page.startsWith("money")) return <Money page={page} o={o} i={i} go={go}/>; if (page.startsWith("cashflow")) return <CashFlow page={page} i={i} open={open}/>; if (page.startsWith("spending")) return <Spending page={page} o={o} i={i} open={open}/>; if (page.startsWith("bills")) return <Bills page={page} i={i} open={open}/>; if (page.startsWith("income")) return <Income page={page} i={i}/>; if (page.startsWith("debt")) return <Debt page={page} i={i}/>; if (page.startsWith("goals")) return <Goals page={page} i={i}/>; if (page.startsWith("roundups")) return <RoundUps i={i}/>; if (page.startsWith("networth")) return <NetWorth page={page} i={i}/>; if (page.startsWith("insights") || page.startsWith("iris")) return <Iris page={page} i={i} findings={findings} open={open} go={go}/>; if (page.startsWith("data")) return <Data page={page} products={products} overview={o}/>; if (page === "reports") return <SimpleWorkspace kicker="REPORTS" heading="Reports are analytical views, not another dashboard." text="Report surfaces will preserve the evidence envelope of the underlying analysis." state="No saved report evidence is currently exposed by the connected data contract."/>; return <SimpleWorkspace kicker="SETTINGS" heading="Control how iBag works for you." text="Settings remain separate from financial interpretation." state="No additional settings are required to interpret the currently observed financial state."/>;
}
function Workspace({ kicker, heading, text, children }: { kicker: string; heading: string; text: string; children: React.ReactNode }) { return <div className="ia-page"><div className="ia-intro"><span>{kicker}</span><h1>{heading}</h1><p>{text}</p></div>{children}</div>; }
function SimpleWorkspace({ kicker, heading, text, state }: { kicker: string; heading: string; text: string; state: string }) { return <Workspace kicker={kicker} heading={heading} text={text}><div className="ia-empty"><b>{state}</b><p>iBag does not manufacture missing evidence. When the underlying contract exposes more data, this workspace can become deeper without changing the meaning of existing observations.</p></div></Workspace>; }
function Home({ o, i, findings, go, open }: any) { const s = i?.cash_flow_safety, c = i?.cash_flow, liquid = i?.net_worth?.liquid_assets; return <Workspace kicker="YOUR FINANCIAL LIFE STATE" heading="Know what matters now." text="Home is the orientation layer. The deeper financial state lives in dedicated workspaces so nothing important has to compete for space."><section className="ia-state"><div className="ia-state-main"><span>LIQUID POSITION <Evidence state={liquid == null ? "insufficient_evidence" : "observed"}/></span><strong>{money(liquid)}</strong><small>As represented by connected evidence</small></div><Metric name="Safe to spend" value={money(s?.safeToSpend)} note={s?.horizonDays ? `${s.horizonDays}-day calculated horizon` : "Evidence limited"}/><Metric name="Net cash flow" value={signed(c?.net)} note="Observed window"/></section><section className="ia-grid two"><article className="ia-feature"><div className="ia-section-head"><span>IRIS PRIORITY</span><button onClick={() => go("iris")}>Open Iris →</button></div>{findings[0] ? <><h2>{findings[0].statement}</h2><button className="ia-link" onClick={() => open(findings[0])}>Explain the evidence →</button></> : <Empty text="No evidence-backed priority finding is currently available."/>}</article><article className="ia-panel"><div className="ia-section-head"><span>WHAT CHANGED</span><button onClick={() => go("insights")}>View insights →</button></div><p className="ia-large-note">{i?.narrative ?? "Iris needs additional evidence before producing a cross-domain synthesis."}</p><Evidence state={i ? "calculated" : "insufficient_evidence"}/></article></section><section className="ia-section"><div className="ia-section-head"><div><span>GO DEEPER</span><h2>Your financial domains</h2></div></div><div className="ia-domain-grid">{["money", "cashflow", "spending", "bills", "income", "debt", "networth", "iris"].map(id => { const p = pages.find(x => x.id === id)!; return <button key={id} onClick={() => go(id)}><b>{p.label}</b><span>{p.description}</span><i>→</i></button>; })}</div></section><section className="ia-section"><div className="ia-section-head"><div><span>RECENT OBSERVATIONS</span><h2>Real activity</h2></div><button onClick={() => go("spending/transactions")}>All transactions →</button></div><TransactionList transactions={(o.recent_transactions ?? []).slice(0, 6)} open={open}/></section></Workspace>; }
function Money({ page, o, i, go }: any) { const accounts = o.accounts ?? []; return <Workspace kicker="MONEY" heading={page === "money" ? "See the structure of your money." : page === "money/accounts" ? "Every connected account." : "Follow financial state through time."} text="Financial objects stay separate from Iris interpretation. Open an account or domain to move from state into detail."><div className="ia-metrics"><Metric name="Liquid assets" value={money(i?.net_worth?.liquid_assets)} note="Observed state"/><Metric name="Revolving debt" value={money(i?.debt_health?.revolvingDebt)} note="Connected evidence"/><Metric name="Credit utilization" value={i?.debt_health?.creditUtilization == null ? "—" : `${(i.debt_health.creditUtilization * 100).toFixed(0)}%`} note="Calculated"/><Metric name="Accounts" value={String(accounts.length)} note="Real provider accounts"/></div><section className="ia-section"><div className="ia-section-head"><div><span>FINANCIAL OBJECTS</span><h2>Connected accounts</h2></div><Evidence state="observed"/></div>{accounts.map((a: any) => <button className="ia-account" key={a.id}><b>{(a.name ?? "A").slice(0, 1)}</b><span><strong>{a.name}</strong><small>{label(a.subtype ?? a.type ?? "account")}{a.mask ? ` · ••••${a.mask}` : ""}</small></span><strong>{money(a.current_balance ?? a.available_balance)}</strong></button>)}</section>{page === "money/timeline" && <Timeline i={i}/>}<div className="ia-related"><button onClick={() => go("networth")}>Net Worth →</button><button onClick={() => go("debt")}>Debt →</button><button onClick={() => go("cashflow")}>Cash Flow →</button></div></Workspace>; }
function CashFlow({ page, i, open }: any) { const s = i?.cash_flow_safety, c = i?.cash_flow, series = i?.forward_projection?.series ?? []; return <Workspace kicker="CASH FLOW" heading={page === "cashflow/forecast" ? "Project liquidity without pretending certainty." : "Follow money through time."} text="Occurred, observed, expected and projected values are intentionally separated."><div className="ia-metrics"><Metric name="Inflows" value={money(c?.inflow)} note={`${c?.windowDays ?? "—"}-day observed window`}/><Metric name="Outflows" value={money(c?.outflow)} note="Observed window"/><Metric name="Net flow" value={signed(c?.net)} note="Observed"/><Metric name="Safe to spend" value={money(s?.safeToSpend)} note="Calculated"/></div><section className="ia-grid two"><article className="ia-panel"><div className="ia-section-head"><span>UPCOMING OBLIGATIONS</span></div>{(s?.upcomingBills ?? []).slice(0, 10).map((b: any, k: number) => <button className="ia-row" key={k} onClick={() => open({ title: "Expected obligation", statement: `${b.merchant} · ${money(b.amount)}`, evidence: "Recurring transaction evidence", state: "calculated", date: b.expectedDate, why: "Iris uses the expected timing to assess upcoming cash-flow pressure." })}><Temporal date={b.expectedDate} role="Expected"/><strong>{money(b.amount)}</strong></button>)}{!s?.upcomingBills?.length && <Empty text="No upcoming obligation is currently evidenced."/>}</article><article className="ia-panel"><div className="ia-section-head"><span>FORWARD MODEL</span><Evidence state="calculated"/></div><p>{i?.forward_projection?.basis ?? "No projection basis is available."}</p>{page === "cashflow/forecast" && series.filter((x: any) => x.event).slice(0, 12).map((x: any) => <button className="ia-row" key={x.date} onClick={() => open({ title: "Projected state", statement: x.event, evidence: i.forward_projection.basis, state: "calculated", date: x.date, why: "This date is part of Iris's calculated forward model." })}><Temporal date={x.date} role="Projected"/><strong>{money(x.balance)}</strong></button>)}</article></section></Workspace>; }
function Spending({ page, o, i, open }: any) { const domains = i?.spending_by_domain ?? [], anomalies = i?.anomalies ?? []; return <Workspace kicker="SPENDING" heading={page === "spending/anomalies" ? "What looks unusual." : page === "spending/transactions" ? "Observed transaction history." : "Understand behavior, not just totals."} text="Spending analysis is derived from observed transactions and preserves uncertainty where classification is not proven.">{page === "spending/transactions" ? <TransactionList transactions={o.recent_transactions ?? []} open={open}/> : <section className="ia-grid two"><article className="ia-panel"><div className="ia-section-head"><span>SPENDING DOMAINS</span><Evidence state="observed"/></div>{domains.map((x: any) => <div className="ia-domain-row" key={x.key}><span><b>{x.label}</b><small>{money(x.amount)}</small></span><strong>{x.changePct == null ? "—" : `${x.changePct > 0 ? "+" : ""}${x.changePct.toFixed(0)}%`}</strong></div>)}</article><article className="ia-panel"><div className="ia-section-head"><span>ANOMALIES</span></div>{anomalies.slice(0, 8).map((a: any, k: number) => <button className="ia-row" key={k} onClick={() => open({ title: "Unusual purchase", statement: `${a.merchant} was ${a.pctAboveTypical}% above typical`, evidence: `Observed ${money(a.amount)} versus typical ${money(a.typicalAmount)}.`, state: "calculated", date: a.date, why: "Iris compared the observation with available merchant history." })}><Temporal date={a.date} role="Occurred"/><strong>{money(a.amount)}</strong></button>)}{!anomalies.length && <Empty text="No significant anomaly is currently evidenced."/>}</article></section>}</Workspace>; }
function Bills({ page, i, open }: any) { const bills = i?.cash_flow_safety?.upcomingBills ?? []; return <Workspace kicker="BILLS & OBLIGATIONS" heading={page === "bills/calendar" ? "Expected pressure by date." : "Know what is coming."} text="An obligation is not treated as paid, guaranteed or causal unless the underlying evidence supports that conclusion."><section className="ia-panel"><div className="ia-section-head"><span>EXPECTED OBLIGATIONS</span><Evidence state="calculated"/></div>{bills.map((b: any, k: number) => <button className="ia-row" key={k} onClick={() => open({ title: "Expected obligation", statement: `${b.merchant} · ${money(b.amount)}`, evidence: "Recurring transaction evidence", state: "calculated", date: b.expectedDate, where: b.merchant, why: "The recurring history supports an expected occurrence, not a guaranteed future payment." })}><Temporal date={b.expectedDate} role="Expected"/><span>{b.merchant}</span><strong>{money(b.amount)}</strong></button>)}{!bills.length && <Empty text="No recurring obligation is currently evidenced."/>}</section></Workspace>; }
function Income({ page, i }: any) { const inc = i?.income ?? i?.income_intelligence; return <Workspace kicker="INCOME" heading={page === "income/history" ? "Income observations through time." : "Understand the inflows that support your state."} text="Income is presented only where the connected evidence and classification support it."><div className="ia-metrics"><Metric name="Observed inflow" value={money(i?.cash_flow?.inflow)} note="Cash-flow window"/><Metric name="Income state" value={inc?.state ? label(inc.state) : "Limited"} note={inc?.evidence ?? "Evidence contract"}/></div><div className="ia-empty"><b>Income detail is evidence-gated.</b><p>iBag will not relabel ordinary inflows as income without sufficient evidence.</p></div></Workspace>; }
function Debt({ page, i }: any) { const d = i?.debt_health; return <Workspace kicker="DEBT" heading={page === "debt/utilization" ? "Understand credit pressure." : "See debt as part of the whole state."} text="Debt is analyzed as an economic relationship, not merely a negative number."><div className="ia-metrics"><Metric name="Revolving debt" value={money(d?.revolvingDebt)} note="Observed/calculated"/><Metric name="Utilization" value={d?.creditUtilization == null ? "—" : `${(d.creditUtilization * 100).toFixed(0)}%`} note="Calculated"/></div><div className="ia-empty"><b>Repayment optimization requires stronger liability evidence.</b><p>Current provider evidence does not justify inventing interest rates, payoff dates or payment schedules.</p></div></Workspace>; }
function Goals({ page, i }: any) { return <SimpleWorkspace kicker="GOALS" heading="Connect intentions to financial evidence." text="Goals are a decision layer, not fabricated account balances." state="No user-defined goal evidence is currently exposed by the connected contract."/>; }
function RoundUps({ i }: any) { return <Workspace kicker="ROUND-UPS" heading="Turn observed purchases into a simulated savings opportunity." text="Phase 1 round-ups are informational only. No money movement occurs."><div className="ia-metrics"><Metric name="Opportunity" value={money(i?.roundup_projection?.opportunity)} note="Calculated from eligible observations"/><Metric name="Allocated" value={money(i?.roundup_projection?.allocated)} note="Simulated"/><Metric name="Projected iBag balance" value={money(i?.roundup_projection?.projected)} note="Simulated only"/></div><div className="ia-empty"><b>Round-Ups never imply a withdrawal.</b><p>Eligibility, calculation and simulated allocation remain distinct evidence states.</p></div></Workspace>; }
function NetWorth({ page, i }: any) { return <Workspace kicker="NET WORTH" heading={page === "networth/history" ? "Net worth through time." : "See the balance between what you have and what you owe."} text="Net worth is derived only from the financial objects currently evidenced."><div className="ia-state"><div className="ia-state-main"><span>LIQUID ASSETS <Evidence state="observed"/></span><strong>{money(i?.net_worth?.liquid_assets)}</strong><small>As of the latest represented state</small></div></div>{page === "networth/history" && <Timeline i={i}/>}</Workspace>; }
function HierarchyIntelligence({ i }: { i: any }) {
  const domains = Array.isArray(i?.spending_hierarchy) ? i.spending_hierarchy : [];
  const risks = Array.isArray(i?.reasoning?.risks) ? i.reasoning.risks : [];
  const opportunities = Array.isArray(i?.reasoning?.opportunities) ? i.reasoning.opportunities : [];
  const relationships = Array.isArray(i?.reasoning?.relationalChain) ? i.reasoning.relationalChain : [];
  const hasContent = domains.length > 0 || risks.length > 0 || opportunities.length > 0 || relationships.length > 0;
  if (!hasContent) return <div className="ia-empty"><b>No certified hierarchy intelligence is currently available.</b><p>IRIS displays hierarchy content only after it is produced from authorized evidence, validated, certified, and published.</p></div>;
  return <section className="ia-section"><div className="ia-section-head"><div><span>HIERARCHY INTELLIGENCE</span><h2>Financial life state → relationships → intelligence</h2></div><Evidence state="calculated"/></div><div className="ia-grid two">
    <article className="ia-panel"><div className="ia-section-head"><span>OBSERVED → CALCULATED DOMAINS</span></div>{domains.map((d: any) => <div className="ia-domain-row" key={d.key}><span><b>{d.label ?? d.key}</b><small>{money(typeof d.amount === "number" ? d.amount : null)}{typeof d.pctOfTotal === "number" ? ` · ${d.pctOfTotal.toFixed(0)}%` : ""}</small></span><strong>{d.changePct == null ? "—" : `${d.changePct > 0 ? "+" : ""}${d.changePct.toFixed(0)}%`}</strong></div>)}</article>
    <article className="ia-panel"><div className="ia-section-head"><span>RELATIONAL CHAIN</span></div>{relationships.length ? relationships.map((x: any, k: number) => <div className="ia-row static" key={k}><span>{String(x)}</span></div>) : <Empty text="No relational chain is currently published."/>}</article>
  </div><div className="ia-grid two">
    <article className="ia-panel"><div className="ia-section-head"><span>RISKS</span></div>{risks.length ? risks.slice(0, 10).map((x: any, k: number) => <div className="ia-row static" key={k}><span><b>{x.statement}</b><small>{x.evidence ?? "Calculated from certified evidence"}</small></span><strong>{x.severity ?? ""}</strong></div>) : <Empty text="No risk finding is currently published."/>}</article>
    <article className="ia-panel"><div className="ia-section-head"><span>OPPORTUNITIES</span></div>{opportunities.length ? opportunities.slice(0, 10).map((x: any, k: number) => <div className="ia-row static" key={k}><span><b>{x.statement}</b><small>{x.evidence ?? "Calculated from certified evidence"}</small></span></div>) : <Empty text="No opportunity finding is currently published."/>}</article>
  </div></section>;
}
function Iris({ page, i, findings, open, go }: any) { const r = i?.reasoning; if (page === "iris/education") return <SimpleWorkspace kicker="IRIS EDUCATION" heading="Learn what your financial state means." text="Education explains concepts without turning missing evidence into certainty." state="Education surfaces are evidence-safe and can expand as the ontology grows."/>; return <Workspace kicker="IRIS" heading={page === "iris/findings" ? "Every finding has a trail." : page === "iris/timeline" ? "Follow relationships across time." : "Iris turns financial evidence into understanding."} text="The hierarchy is one complete financial life state: observations, calculations, relationships, findings and higher-order intelligence are displayed together when certified."><HierarchyIntelligence i={i}/><section className="ia-feature"><span>IRIS SYNTHESIS</span><h2>{i?.narrative ?? "Iris needs more evidence for a synthesis."}</h2><Evidence state={i ? "calculated" : "insufficient_evidence"}/></section><section className="ia-grid two"><FindingPanel title="Risks" items={r?.risks ?? []} open={open}/><FindingPanel title="Opportunities" items={r?.opportunities ?? []} open={open}/></section><div className="ia-related"><button onClick={() => go("iris/education")}>Learn from this state →</button><button onClick={() => go("cashflow/forecast")}>Explore the forward model →</button></div></Workspace>; }
function FindingPanel({ title, items, open }: any) { return <article className="ia-panel"><div className="ia-section-head"><span>{title}</span></div>{items.slice(0, 10).map((x: any, k: number) => <button className="ia-finding" key={k} onClick={() => open({ title, statement: x.statement, evidence: x.evidence, state: "calculated", why: "This finding is produced by Iris from available evidence and reasoning rules." })}><b>{x.statement}</b><span>Explain →</span></button>)}{!items.length && <Empty text={`No ${title.toLowerCase()} are currently evidenced.`}/>}</article>; }
function Data({ page, products, overview }: any) { const p = products ?? {}; return <Workspace kicker="DATA & PLAID" heading={page === "data/evidence" ? "Evidence and provenance." : page === "data/sync" ? "Observed synchronization." : "See the provider boundary clearly."} text="This workspace describes source data and coverage. Iris interpretation stays outside the provider layer."><div className="ia-metrics"><Metric name="Accounts" value={String(overview.accounts?.length ?? 0)} note="Observed provider objects"/><Metric name="Transactions" value={String(overview.recent_transactions?.length ?? 0)} note="Returned by current overview"/><Metric name="Provider products" value={String(p.products?.length ?? p.billed_products?.length ?? 0)} note="Provider metadata"/></div><section className="ia-panel"><div className="ia-section-head"><span>PRODUCT COVERAGE</span><Evidence state="observed"/></div>{(p.products ?? p.billed_products ?? []).map((x: any, k: number) => <div className="ia-product" key={k}><b>{x.name ?? x.product ?? x}</b><span>{x.status ?? x.state ?? "Provider metadata"}</span></div>)}{!(p.products ?? p.billed_products)?.length && <Empty text="No product detail was returned by the current provider contract."/>}</section></Workspace>; }
function Timeline({ i }: any) { const series = i?.forward_projection?.series ?? []; return <section className="ia-section"><div className="ia-section-head"><div><span>TIME</span><h2>Financial timeline</h2></div><Evidence state="calculated"/></div>{series.filter((x: any) => x.event).slice(0, 12).map((x: any) => <div className="ia-row static" key={x.date}><Temporal date={x.date} role="Projected"/><span>{x.event}</span><strong>{money(x.balance)}</strong></div>)}</section>; }
function TransactionList({ transactions, open }: any) { return <div className="ia-list">{transactions.map((t: any) => <button className="ia-row" key={t.id} onClick={() => open({ title: "Transaction observation", statement: t.name ?? t.merchant_name ?? "Transaction", evidence: "Observed transaction record", state: "observed", date: t.date, where: t.merchant_name ?? t.name, why: "This is a provider-backed transaction observation; its economic meaning depends on classification evidence." })}><Temporal date={t.date} role="Occurred"/><span><b>{t.merchant_name ?? t.name ?? "Transaction"}</b><small>{label(t.category ?? t.type ?? "transaction")}</small></span><strong>{money(t.amount)}</strong></button>)}</div>; }
function Empty({ text }: { text: string }) { return <div className="ia-empty"><span>{text}</span></div>; }
function Connect({ onConnect }: { onConnect: () => void }) { return <div className="ia-connect"><IrisMark size={50} color="#111"/><h1>Connect your financial evidence.</h1><p>Iris cannot build a financial life state without authorized source data.</p><PlaidLinkButton onSuccess={onConnect}/></div>; }
function EvidenceDrawer({ finding, close }: { finding: Finding; close: () => void }) { return <div className="ia-drawer-wrap" onClick={close}><aside className="ia-drawer" onClick={e => e.stopPropagation()}><button className="ia-close" onClick={close}>×</button><span>EXPLANATION</span><h2>{finding.title}</h2><h3>{finding.statement}</h3><div className="ia-drawer-block"><small>STATE</small><Evidence state={finding.state}/></div>{finding.date && <div className="ia-drawer-block"><small>WHEN</small><Temporal date={finding.date} role="Observed"/></div>}{finding.where && <div className="ia-drawer-block"><small>WHERE / WHO</small><p>{finding.where}</p></div>}{finding.evidence && <div className="ia-drawer-block"><small>EVIDENCE</small><p>{finding.evidence}</p></div>}<div className="ia-drawer-block"><small>WHY IT MATTERS</small><p>{finding.why ?? "Iris has not supplied an additional causal explanation."}</p></div><div className="ia-drawer-block"><small>BOUNDARY</small><p>Iris does not convert temporal precedence into causality and does not treat inference as observation.</p></div></aside></div>; }
