import { useEffect, useMemo, useState } from "react";
import { api } from "../api/backend";
import "./IrisHierarchyExperience.css";

type Field = { field_key: string; label: string; value: unknown; value_type?: string; evidence_state?: string; derivation_operator?: string };
type Domain = { domain_key: string; evidence_state: string; canonical_fields?: Field[]; derived_fields?: Field[]; relationships?: any[]; domain_intelligence?: any[]; limitations?: string[] };
type Cross = { key: string; name: string; domains: string[]; state: string; value: Record<string, unknown> };
type Level2 = { certified?: boolean; level: number; evidence_boundary?: string; domains?: Domain[]; cross_domain?: Cross[]; materialized?: { nodes: number; edges: number; compositions: number } };

const names: Record<string, string> = { authentication: "Connections", transactions: "Transactions", balance: "Balance", identity: "Identity", assets: "Assets", liabilities: "Liabilities", investments: "Investments", statements: "Statements" };
const money = (v: unknown) => typeof v === "number" && Number.isFinite(v) ? `${v < 0 ? "−" : ""}$${Math.abs(v).toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : v == null ? "—" : String(v);
const pretty = (key: string) => key.replace(/_/g, " ").replace(/\b\w/g, c => c.toUpperCase());
const show = (v: unknown, type?: string) => type === "currency" ? money(v) : v == null ? "Insufficient evidence" : typeof v === "object" ? JSON.stringify(v) : String(v);
function State({ state }: { state?: string }) { const s = (state ?? "INSUFFICIENT_EVIDENCE").toLowerCase(); return <span className={`ih-state ${s}`}>{pretty(s)}</span>; }
function FieldValue({ field }: { field: Field }) { return <article className="ih-field"><div><span>{field.label}</span><State state={field.evidence_state}/></div><strong>{show(field.value, field.value_type)}</strong><small>{field.derivation_operator ? pretty(field.derivation_operator) : "Observed financial state"}</small></article>; }

export function IrisHierarchyExperience() {
  const [data, setData] = useState<Level2 | null>(null); const [active, setActive] = useState("overview"); const [error, setError] = useState<string | null>(null); const [running, setRunning] = useState(true);
  const load = async () => { setError(null); setRunning(true); try { let current = await api.getIrisLevel2(); if (!current?.certified) { const result = await api.runIrisLevel2(); if (result?.certification_status !== "CERTIFIED") throw new Error("IRIS could not certify the current financial hierarchy."); current = await api.getIrisLevel2(); } if (!current?.certified) throw new Error("The certified IRIS hierarchy is not available."); setData(current); } catch (e) { setError(e instanceof Error ? e.message : "IRIS could not load the current hierarchy."); } finally { setRunning(false); } };
  useEffect(() => { void load(); }, []);
  const domains = data?.domains ?? []; const selected = domains.find(d => d.domain_key === active); const cross = data?.cross_domain ?? [];
  const connections = useMemo(() => cross.filter(x => x.domains.length >= 2), [cross]);
  if (running) return <main className="ih-loading"><div className="ih-orb">I</div><h1>IRIS</h1><p>Assembling your connected financial life…</p></main>;
  if (error || !data) return <main className="ih-loading"><div className="ih-orb">I</div><h1>IRIS</h1><p>{error ?? "Your financial state could not be loaded."}</p><button onClick={() => void load()}>Try again</button></main>;
  return <main className="ih-app">
    <header className="ih-header"><div className="ih-brand"><div className="ih-mark">I</div><div><b>IRIS</b><span>Financial life intelligence</span></div></div><div className="ih-header-state"><span className="ih-live"/>Current state <State state="OBSERVED"/></div></header>
    <div className="ih-layout"><aside className="ih-nav"><div className="ih-nav-title">Your financial life</div><button className={active === "overview" ? "active" : ""} onClick={() => setActive("overview")}>Overview</button>{domains.map(d => <button key={d.domain_key} className={active === d.domain_key ? "active" : ""} onClick={() => setActive(d.domain_key)}>{names[d.domain_key] ?? pretty(d.domain_key)}<State state={d.evidence_state}/></button>)}</aside>
      <section className="ih-content">{active === "overview" ? <>
        <div className="ih-hero"><div><span className="ih-eyebrow">Your financial life</span><h1>See the relationships,<br/>not just the numbers.</h1><p>IRIS organizes authorized financial evidence into a living, relational state. As you move through it, connected intelligence stays in context.</p></div><div className="ih-core"><div className="ih-core-ring">IRIS</div>{domains.map((d, i) => <i key={d.domain_key} style={{ ["--i" as any]: i }}/>)}</div></div>
        <section className="ih-section"><div className="ih-section-head"><div><span className="ih-eyebrow">Connected state</span><h2>The financial picture</h2></div><span>{domains.length} domains</span></div><div className="ih-domain-strip">{domains.map(d => <button key={d.domain_key} onClick={() => setActive(d.domain_key)}><span>{names[d.domain_key] ?? pretty(d.domain_key)}</span><State state={d.evidence_state}/><b>{(d.derived_fields ?? []).length + (d.domain_intelligence ?? []).length}</b><small>intelligence elements</small></button>)}</div></section>
        <section className="ih-section"><div className="ih-section-head"><div><span className="ih-eyebrow">Combinations</span><h2>Where your financial state connects</h2></div><span>{connections.length} relationships</span></div><div className="ih-connections">{connections.length ? connections.map(c => <article key={c.key}><div className="ih-connection-nodes">{c.domains.map(d => <span key={d}>{names[d] ?? pretty(d)}</span>)}</div><h3>{c.name}</h3><p>{Object.entries(c.value).filter(([k]) => k !== "evidence_boundary").map(([k,v]) => <span key={k}><b>{pretty(k)}</b>{money(v)}</span>)}</p><State state={c.state}/></article>) : <div className="ih-empty">No cross-domain relationship is supported by the certified evidence.</div>}</div></section>
        <section className="ih-section"><div className="ih-section-head"><div><span className="ih-eyebrow">Relational view</span><h2>Follow the financial state</h2></div><span>{data.materialized?.nodes ?? 0} nodes · {data.materialized?.edges ?? 0} relationships</span></div><div className="ih-graph"><div className="ih-graph-center">IRIS<span>financial life</span></div>{domains.map((d, i) => <button key={d.domain_key} style={{ ["--i" as any]: i }} onClick={() => setActive(d.domain_key)}>{names[d.domain_key] ?? pretty(d.domain_key)}</button>)}</div></section>
      </> : <>
        <div className="ih-domain-hero"><span className="ih-eyebrow">Financial life</span><h1>{names[selected?.domain_key ?? active] ?? pretty(active)}</h1><p>{selected?.limitations?.[0] ?? "IRIS is organizing the evidence and relationships available for this part of your financial life."}</p><State state={selected?.evidence_state}/></div>
        <section className="ih-section"><div className="ih-section-head"><div><span className="ih-eyebrow">Derived state</span><h2>What IRIS can establish</h2></div></div><div className="ih-fields">{(selected?.derived_fields ?? []).map(f => <FieldValue key={f.field_key} field={f}/>)}</div></section>
        <section className="ih-section"><div className="ih-section-head"><div><span className="ih-eyebrow">Observed records</span><h2>Underlying domain content</h2></div></div><div className="ih-fields">{(selected?.canonical_fields ?? []).slice(0, 24).map(f => <FieldValue key={f.field_key} field={f}/>)}</div></section>
        <section className="ih-section"><div className="ih-section-head"><div><span className="ih-eyebrow">Relationships</span><h2>Connected to</h2></div></div><div className="ih-related">{(selected?.relationships ?? []).length ? selected?.relationships?.map((r, i) => <article key={i}><b>{pretty(r.relation_type ?? "relationship")}</b><span>{Object.entries(r).filter(([k]) => k !== "relation_type").map(([k,v]) => `${pretty(k)}: ${String(v)}`).join(" · ")}</span></article>) : <div className="ih-empty">No additional relationship is supported by the certified evidence.</div>}</div></section>
        <section className="ih-section"><div className="ih-section-head"><div><span className="ih-eyebrow">Cross-domain intelligence</span><h2>What this connects to</h2></div></div><div className="ih-connections">{connections.filter(c => c.domains.includes(active)).map(c => <article key={c.key}><div className="ih-connection-nodes">{c.domains.map(d => <span key={d}>{names[d] ?? pretty(d)}</span>)}</div><h3>{c.name}</h3><p>{Object.entries(c.value).filter(([k]) => k !== "evidence_boundary").map(([k,v]) => <span key={k}><b>{pretty(k)}</b>{money(v)}</span>)}</p><State state={c.state}/></article>)}</div></section>
      </>}
      <footer className="ih-footer">Current state · {data.evidence_boundary ? new Date(data.evidence_boundary).toLocaleString("en-US") : "date not observed"}</footer>
      </section></div>
  </main>;
}
