import { useEffect, useState } from "react";
import { api } from "../api/backend";
import type { IrisConsumerIntelligenceResponse } from "../contracts/irisConsumer";
import "./IrisIntelligenceScreens.css";

type Props = { go?: (page: string) => void };
export function IrisActionSurface({ go }: Props) {
  const [intel, setIntel] = useState<IrisConsumerIntelligenceResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { let live = true; api.getIntelligence().then(x => { if (live) setIntel(x); }).catch(e => { if (live) setError(e instanceof Error ? e.message : "Action context could not be loaded."); }); return () => { live = false; }; }, []);
  const certified = intel?.certified === true && intel.certification_gate?.eligible === true;
  const reasoning = certified ? intel?.reasoning : null;
  return <main className="iis-screen"><section className="iis-hero"><span>IRIS · ACTION</span><h1>Action boundary</h1><p>Action begins only after evidence, understanding and a decision. The current product is read-only, so IRIS does not execute bank, card, payment, transfer or investment actions.</p></section>{error && <section className="iis-panel"><span>EVIDENCE STATUS</span><h2>Action context unavailable</h2><p>{error}</p></section>}<section className="iis-metric-grid"><article className="iis-metric"><span>Decision context</span><strong>{certified ? "Available" : "—"}</strong><small>{certified ? "Certified intelligence" : "Certification required"}</small></article><article className="iis-metric"><span>Risks</span><strong>{reasoning ? reasoning.risks.length : "—"}</strong><small>Live governed input</small></article><article className="iis-metric"><span>Opportunities</span><strong>{reasoning ? reasoning.opportunities.length : "—"}</strong><small>Live governed input</small></article></section>{reasoning && <section className="iis-panel"><span>GOVERNED INPUTS</span><h2>What an eventual action would need to consider</h2><div className="iis-catalog-grid">{reasoning.risks.map(r => <article className="iis-catalog-card" key={r.key}><div><span>RISK · {r.severity.toUpperCase()}</span><b>{r.key}</b></div><small>{r.statement}</small></article>)}{reasoning.opportunities.map(x => <article className="iis-catalog-card" key={x.key}><div><span>OPPORTUNITY</span><b>{x.key}</b></div><small>{x.statement}</small></article>)}</div></section>}{!certified && <section className="iis-panel"><span>NO EXECUTION</span><h2>IRIS will not invent an action</h2><p>Without certified decision context, no action recommendation is published. Even with certified context, Phase 1 remains read-only and requires a future explicit authorization and execution contract.</p></section>}<section className="iis-panel"><h2>Action → Outcome</h2><div className="iis-catalog-toolbar"><button onClick={() => go?.("iris/decisions")}>Review decision →</button><button onClick={() => go?.("iris/evidence")}>Verify evidence →</button><button onClick={() => go?.("iris/outcomes")}>View observed outcomes →</button></div></section></main>;
}
